### ISSUE TITLE
Add initial caps method names to CsoundOboe and expose them to JavaScript

### ISSUE THREAD

**Issue by gogins** [gogins/csound-android#1]
This is to make the Csound class method API that is exposed to JavaScript consistent across my supported platforms: Csound for WebAssembly, csound.node, and the Csound for Android app.

The preference is for initial caps (e.g. `csound.CompileCsdText`) as opposed to camel case (e.g. `csound.compileCsdText`).

The reason for this is to follow the naming conventions used in the canonical Csound `csound.hpp` C++ interface declaration, and thus to enable working on the same pieces in any of these environments without changing the code.

This work should be tested using the examples listed in csound-extended issue 133.

**Comment by gogins** [comment]
In addition, the build system and code should be refactored to get rid of my hack with CsoundAndroid appearing twice.

**Comment by gogins** [comment]
Changing Csound.setChannel(char *, double) to csound.SetChannel(char *, double) produces this runtime error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.csounds.Csound6, PID: 19194
    java.lang.UnsatisfiedLinkError: No implementation found for void csnd.csound_oboeJNI.CsoundOboe_SetChannel(long, csnd.CsoundOboe, java.lang.String, double) (tried Java_csnd_csound_1oboeJNI_CsoundOboe_1SetChannel and Java_csnd_csound_1oboeJNI_CsoundOboe_1SetChannel__JLcsnd_CsoundOboe_2Ljava_lang_String_2D)
        at csnd.csound_oboeJNI.CsoundOboe_SetChannel(Native Method)
        at csnd.CsoundOboe.SetChannel(CsoundOboe.java:390)
        at com.csounds.Csound6.CsoundAppActivity$6.onSensorChanged(CsoundAppActivity.java:919)
        at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:1017)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:7080)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```
Csound runs fine otherwise as far as I can tell.

**Comment by gogins** [comment]
The initial caps are done. Refactoring seems to be very difficult for me.

**Comment by gogins** [comment]
- [ ] On Android, the message callback is not being called.
- [ ] On Android, scrims.html is not working, probably due to the scope of the csound object.

**Comment by gogins** [comment]
I have removed the old CsoundAndroid C++ class and rtopensl code from this repository.
